CC=clang
CFLAGS=-std=c11 -Wall -O2

TARGET_NAME=iotest

SRC_DIRECTORY=src

SOURCE_FILES=\
	$(SRC_DIRECTORY)/$(TARGET_NAME).c

INCLUDE_DIRECTORIES=

SYMBOLS=

BUILD_DIRECTORY=build

all: clean default

default: $(TARGET_NAME)

$(TARGET_NAME):
	$(CC) $(CFLAGS) $(INCLUDE_DIRECTORIES) $(SYMBOLS) $(SOURCE_FILES) -o $(BUILD_DIRECTORY)/$(TARGET_NAME)

clean:
	rm -f $(BUILD_DIRECTORY)/$(TARGET_NAME)
	rm -rf $(TARGET_NAME).dSYM
